version: '3.1'

volumes:
  redis-data: {}

services:

  redis-sentinel:
    image: destinationbook/redis-sentinel:${TAG:-latest}
    environment:
      - REDIS_SERVICE_NAME=redis
      - REDIS_MASTER_NAME=redismaster
    deploy:
      replicas: 3
      endpoint_mode: dnsrr

  redis:
    image: destinationbook/redis-look:${TAG:-latest}
    environment:
      - QUORUM=2
      - REDIS_SERVICE_NAME=redis
    volume:
      - redis-data:/data
    deploy:
      replicas: 3
      endpoint_mode: dnsrr
