version: '3.3'

networks:
  redisnet:
        driver: overlay
        attachable: true
volumes:
  redis-data: {}

services:

  redis-sentinel:
    image: destinationbook/redis-sentinel:${TAG:-latest}
    environment:
      - REDIS_SERVICE_NAME=redis
      - REDIS_MASTER_NAME=redismaster
    networks:
      - redisnet
    deploy:
      replicas: 3
      endpoint_mode: dnsrr

  redis:
    image: destinationbook/redis-look:${TAG:-latest}
    environment:
      - QUORUM=2
      - REDIS_SERVICE_NAME=redis
    networks:
      - redisnet
    volumes:
      - redis-data:/data
    deploy:
      replicas: 3
      endpoint_mode: dnsrr
